- src/notice.ts
- test/notices.test.ts
- test/schema.test.ts
Rearchitects the tests a little so that the individual validation failures are clearly scoped and presented by Jest.
> fix: test that version ranges are bounded at the top

- data/notices.json
Adding a notice for IAM/EKS OIDC Issue where the OIDC provider currently is retrieving short lived leaf certificates instead of root certificates which have a longer expiration date.
> chore: notice for https://github.com/aws/aws-cdk/issues/8607

- data/notices.json
Now that we have fixed version, we can put a upper bound on the notice. 
See https://github.com/aws/aws-cdk/releases/tag/v2.51.0 and https://github.com/aws/aws-cdk/releases/tag/v1.181.0
> chore: upper minor bound for OIDC notice

- data/notices.json
Reverts cdklabs/aws-cdk-notices#23
This bump caused an HTTP cert & thumbprint miss-match error. Reverting until this is fixed.
Currently blocking:
- https://github.com/cdklabs/aws-cdk-notices/actions/runs/3522519119 
Related TT: V772158739
> fix: revert "chore: upper minor bound for OIDC notice"

- .eslintrc.json
- .projen/deps.json
- .projen/tasks.json
- .projenrc.ts
- package.json
- tsconfig.dev.json
- yarn.lock
Fixes the broken `deploy` workflow once deployed.
Also migrates projen config to a ts file.
> fix: set min aws-cdk version to 2.51.0 so the OIDC thumbprint bug is definitely fixed

- data/notices.json
CLI notice for WAFv2 RuleGroup struct name changes. 
Being patched here: https://github.com/aws/aws-cdk/pull/24651
> chore: notice for https://github.com/aws/aws-cdk/issues/24668

- data/notices.json
CLI notice for #25130. Stack names have been modified in a breaking way if they use special characters.
> chore: notice for https://github.com/aws/aws-cdk/issues/25130

- data/notices.json
CLI notice for #24358. Inactive custom resource provider framework lambdas will cause errors due to Lambda's default SDK version (2.1055.0) not having `functionActiveV2` which only exists on 2.1080.0 and up.
> chore: notice for https://github.com/aws/aws-cdk/issues/24358

- data/notices.json
All CDK versions <2.60.0 are impacted (that's when we introduced the feature flag).
Since we can't check on feature flags in the CLI notices, alert only the definitely impacted crowd.
Fixes #
> chore: notice for https://github.com/aws/aws-cdk/issues/25358

- data/notices.json
- test/schema.test.ts
Since there are two separate problems, introduced in two separate commits, issue two notices based on the affeceted versions. Note that we have no way of knowing if customers are actually impacted by the default masters role because we don't know if they pass the `mastersRole` property or not.
> chore: notice for https://github.com/aws/aws-cdk/issues/25674

- .projen/deps.json
- .projenrc.ts
- package.json
- yarn.lock
Related: https://github.com/cdklabs/aws-cdk-notices/security/dependabot/9
> chore: Bump aws-cdk version

- data/notices.json
We don't have a way of targeting specific languages, so this is going to blast all users not just python ones.
> chore: notice for https://github.com/aws/aws-cdk/issues/27259

- README.md
- data/notices.json
Notice for https://github.com/aws/aws-cdk/issues/28465
> chore: notice for https://github.com/aws/aws-cdk/issues/28465

- data/notices.json
Notice for [#28520](https://github.com/aws/aws-cdk/issues/28520)
> chore: notice for https://github.com/aws/aws-cdk/issues/28520

- data/notices.json
Adds a warning to let users know that they should set the `@aws-cdk/custom-resources:logApiResponseDataPropertyTrueDefault` feature flag to true if upgrading to a CDK version >2.144.0 from a CDK version >=2.138.0 <=2.144.0.
> chore: add feature flag warning to notice for https://github.com/aws/aws-cdk/issues/29949

- data/notices.json
Update notice for https://github.com/aws/aws-cdk/issues/30444
> chore: notice for https://github.com/aws/aws-cdk/issues/30444

- data/notices.json
According to README, if we want to use the module name, we need to include `.` at the end.
https://github.com/cdklabs/aws-cdk-notices?tab=readme-ov-file#structure
> fix: update the names to include suffix .

- README.md
Should be merged after https://github.com/aws/aws-cdk/pull/31555.
Documenting new capabilities.
> feat: notices on bootstrap version

- data/notices.json
- src/notice.ts
adds a check and fixes a bad notice.
> fix: notices must have non-empty properties

- data/notices.json
- src/construct-info.ts
- src/notice.ts
- test/schema.test.ts
> chore: notice for https://github.com/aws/aws-cdk/issues/31885

- data/notices.json
- yarn.lock
This targets cdk CLI versions 2.1005.0 and below, requiring acknowledgement from users to dismiss. Before users upgrade it serves as an advanced notice. After users upgrade, it serves to preempt the question "Why are my versions different now?"
> feat: notice for https://github.com/aws/aws-cdk/issues/32775

- data/notices.json
Send out notice to any customers currently using versions of the construct before its latest iteration (pre-2.179.0) to bump to latest and ensure we have decent adoption and coverage.
> chore: add notice about Cognito Identity Pools soon to be GA

- data/notices.json
The notice has not been visible yet, likely due to the way alpha modules are versioned slightly differently. This PR aims to update that versioning of this notice.
> chore: fix Cognito Identity Pool versioning

- data/notices.json
Notify users of the construct to upgrade their CDK version for awareness and to minimize disruption when the modules are graduated.
> chore: add notice about Scheduler alpha modules soon to be GA

- data/notices.json
- src/construct-info.ts
- yarn.lock
Relies  on Node matching support for notices: https://github.com/aws/aws-cdk-cli/pull/128
> chore: add notice for Node 14.x and 16. deprecations

- data/notices.json
- test/schema.test.ts
Includes a fix to tests not actually failing if an issue doesn't exists.
Also changes that check to allow a redirect status. This is needed because `https://github.com/aws/aws-cdk/issues/34205` has been transferred to `aws/aws-cdk-cli` and will return a redirect response.
> feat: notice for https://github.com/aws/aws-cdk/issues/34205

- data/notices.json
We actually want to do an `AND` between library and CLI versions, but currently `components` only allows us doing an `OR`.
So I'm alerting on the most specific version here, which I think is going to be the library version number.
> chore: notice for https://github.com/aws/aws-cdk/issues/34885

- data/notices.json
Notice is sent to everyone for visibility so make it clear that telemetry is collected on new versions after 8/8/25 only.
> chore: update notice 34892

- data/notices.json
Adds information about https://github.com/aws/aws-cdk-cli/pull/631.
> chore: update notice 34892 with information on how to log telemetry to a local file
