- data/notices.json
- test/schema.test.ts
> fix: another version boundedness assertion

- data/notices.json
references [23407](https://github.com/aws/aws-cdk/issues/23407).
> chore: notice for https://github.com/aws/aws-cdk/issues/23407

- data/notices.json
rephrase message to be more clear
> chore: Clarify notice phrasing for #23407

- data/notices.json
> chore: notice for https://github.com/aws/aws-cdk/issues/25356

- data/notices.json
only affects cli version 2.80.0
issue: https://github.com/aws/aws-cdk/issues/25714
> chore: notice for https://github.com/aws/aws-cdk/issues/25714

- data/notices.json
issue: https://github.com/aws/aws-cdk/issues/25714
A further issues was discovered and fixed in 2.83.1
> chore: update notice for https://github.com/aws/aws-cdk/issues/25714

- data/notices.json
> chore: notice for https://github.com/aws/aws-cdk/issues/26325

- data/notices.json
Add a new notice about CDK V1 EOL that is stronger worded.
> feat: The inevitable Death of CDK V1

- data/notices.json
Notice for https://github.com/aws/aws-cdk/issues/28165
> chore: notice for https://github.com/aws/aws-cdk/issues/28165

- data/notices.json
Adds a notice for high-impact issue aws/aws-cdk#28577.
> chore: add notice for aws/aws-cdk#28577

- data/notices.json
Fixes #[29420](https://github.com/aws/aws-cdk/issues/29420)
> chore: notice for https://github.com/aws/aws-cdk/issues/29420

- data/notices.json
CDK CLI notice for: https://github.com/aws/aws-cdk/issues/29483
> chore: notice for https://github.com/aws/aws-cdk/issues/29483

- data/notices.json
CDK CLI notice for https://github.com/aws/aws-cdk/issues/29610
> chore: notice for https://github.com/aws/aws-cdk/issues/29610

- data/notices.json
> chore: notice for https://github.com/aws/aws-cdk/issues/30008

- data/notices.json
Fixes # [30093](https://github.com/aws/aws-cdk/pull/30093)
> chore: notice for https://github.com/aws/aws-cdk/issues/30241

- data/notices.json
Fixes [#30143](https://github.com/aws/aws-cdk/issues/30143)
> chore: notice for aws/aws-cdk#30143

- data/notices.json
CDK CLI notice for https://github.com/aws/aws-cdk/issues/29949
> chore: notice for https://github.com/aws/aws-cdk/issues/29949

- data/notices.json
CDK CLI notice for https://github.com/aws/aws-cdk/issues/30669
> chore: notice for https://github.com/aws/aws-cdk/issues/30669

- data/notices.json
Update notice for https://github.com/aws/aws-cdk/issues/30717
> chore: notice for https://github.com/aws/aws-cdk/issues/30717

- data/notices.json
Update notice for https://github.com/aws/aws-cdk/issues/31106
> chore: notice for https://github.com/aws/aws-cdk/issues/31106

- data/notices.json
Update notice for https://github.com/aws/aws-cdk/issues/31183
> chore: notice for https://github.com/aws/aws-cdk/issues/31183

- data/notices.json
Update notice for https://github.com/aws/aws-cdk/issues/31302
> chore: notice for https://github.com/aws/aws-cdk/issues/31302

- data/notices.json
> fix: update the names to match construct info name

- data/notices.json
> chore: add ecs patterns breaking change notice

- data/notices.json
Update notice for  https://github.com/aws/aws-cdk/issues/31654
> chore: notice for https://github.com/aws/aws-cdk/issues/31654

- data/notices.json
> chore: Update notices.json

- data/notices.json
- package.json
- yarn.lock
> chore: notice for issue 32510.

- data/notices.json
> chore: notice for issue 32653

- data/notices.json
> chore: notice for issue 28518

- data/notices.json
> Notice for issue 32836

- data/notices.json
Relates to https://github.com/aws/aws-cdk/issues/33320
> feat: notice for issue 33320

- .gitignore
- data/notices.json
Notice for https://github.com/aws/aws-cdk/issues/33768
> chore: notice for https://github.com/aws/aws-cdk/issues/33768

- data/notices.json
Fixes https://github.com/aws/aws-cdk/issues/34157
> chore: notice for https://github.com/aws/aws-cdk/issues/34157

- data/notices.json
Fixes https://github.com/aws/aws-cdk/issues/34293
> chore: notice for https://github.com/aws/aws-cdk/issues/34293

- data/notices.json
chore: notice for aws/aws-cdk#34293
> chore: notice for aws/aws-cdk#34293

- data/notices.json
notice for https://github.com/aws/aws-cdk/issues/34486
> chore: notice for https://github.com/aws/aws-cdk/issues/34486

- data/notices.json
Notice for https://github.com/aws/aws-cdk/issues/34739
> chore: notice for OpenSearch domain TLSSecurityPolicy default value
